linters:
  disable-all: true
  enable:
    - loglint

linters-settings:
  custom:
    loglint:
      type: module
      description: "My custom linter"
      original-url: github.com/Nishiramirai/loglint