linters-settings:
  custom:
    loglint:
      type: module
      description: Linter for checking log messages rules
      original-url: github.com/Nishiramirai/loglint
      settings: {}

linters:
  disable-all: true
  enable:
    - custom