version: "2"  # Оставляем, это важно для custom-бинарника

linters:
  disable-all: true
  enable:
    - loglint  # Это имя должно совпадать с полем Name в твоем analysis.Analyzer

linters-settings:
  custom:
    loglint:
      type: "module"
      description: "My custom linter"
      # УДАЛИ отсюда original-url и settings на время теста